=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/yogas/YogaConfigGroup.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT YogaConfigGroup (YogaConfig)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT YogaConfig (Rule|AllowHigherVargas|Group|Source|Effect|Description)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Effect (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Source (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Group (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AllowHigherVargas (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Rule (#PCDATA)>

=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/yogas/41NakshtrasBrihatJataka.xml
<?xml version="1.0"?>
<!DOCTYPE YogaConfigGroup SYSTEM "YogaConfigGroup.dtd">
<YogaConfigGroup>
	<!--  1  -->
	<YogaConfig>
		<Description>Moon in Aswini</Description>
		<Effect>The person born In Aswini will be fond of decoration, handsome, popular, skilful and intelligent </Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Aswini;</Rule>
	</YogaConfig>

	<!--  2  -->
	<YogaConfig>
		<Description>Moon in Bharani</Description>
		<Effect>One born in Bharani will be determined, truthful, healthy, skilful and happy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Bharani;</Rule>
	</YogaConfig>

	<!--  3  -->
	<YogaConfig>
		<Description>Moon in Krittika</Description>
		<Effect>The person born in Krittika will be a voracious enter, fond of otherâ€™s wives, attractive and renowned </Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Krittika;</Rule>
	</YogaConfig>

	<!--  4  -->
	<YogaConfig>
		<Description>Moon in Rohini</Description>
		<Effect>Rohini makes a man truthful, clean, following religious and moral principles, sweet in speech, fixed mind and handsome.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Rohini;</Rule>
	</YogaConfig>

	<!--  5  -->
	<YogaConfig>
		<Description>Moon in Mrigasira</Description>
		<Effect>Mrigasira-Capricious, skilful, cowardly, good speaker, hopeful, rich and enjoying.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Mrigasira;</Rule>
	</YogaConfig>

	<!--  6  -->
	<YogaConfig>
		<Description>Moon in Arudra</Description>
		<Effect>Aridra-Dissimulating in self-interest, proud, ungrateful, cruel and sinful.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Arudra;</Rule>
	</YogaConfig>

	<!--  7  -->
	<YogaConfig>
		<Description>Moon in Punarvasu</Description>
		<Effect>Punarvasu-Religious endurance, happy, good, dull, sickly, thirsty and pleased with small gifts.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Punarvasu;</Rule>
	</YogaConfig>

	<!--  8  -->
	<YogaConfig>
		<Description>Moon in Pushyami</Description>
		<Effect>Pushya-Control over passions, popular, learned, rich and charitable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Pushyami;</Rule>
	</YogaConfig>

	<!--  9  -->
	<YogaConfig>
		<Description>Moon in Aslesha</Description>
		<Effect>Aslesha-Dissimulator, clever in selfishness, sinful, ungrateful and a cheat.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Aslesha;</Rule>
	</YogaConfig>

	<!--  10  -->
	<YogaConfig>
		<Description>Moon in Makha</Description>
		<Effect>Makha-Many servants and great wealth, enjoying, respector of elders and gods and very enterprising.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Makha;</Rule>
	</YogaConfig>

	<!--  11  -->
	<YogaConfig>
		<Description>Moon in Purva Phalgini</Description>
		<Effect>Pubba-Sweet speech, liberal, handsome, fond of traveling and royal servant.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaPhalgini;</Rule>
	</YogaConfig>

	<!--  12  -->
	<YogaConfig>
		<Description>Moon in Uttara Phalguni</Description>
		<Effect>Uttara-Popular, self-acquired property, enjoying and happy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraPhalguni;</Rule>
	</YogaConfig>

	<!--  13  -->
	<YogaConfig>
		<Description>Moon in Hashta</Description>
		<Effect>Hasta-Enterprising, intelligent or (shameless), drunkard, cruel and thievish.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Hashta;</Rule>
	</YogaConfig>

	<!--  14  -->
	<YogaConfig>
		<Description>Moon in Chitta</Description>
		<Effect>Chitta-Using various clothes and garlands, good looks and limbs.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Chitta;</Rule>
	</YogaConfig>

	<!--  15  -->
	<YogaConfig>
		<Description>Moon in Swati</Description>
		<Effect>Swati-Polite, merchant, kind hearted, not able to endure thirst, sweet tongued and generous.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Swati;</Rule>
	</YogaConfig>

	<!--  16  -->
	<YogaConfig>
		<Description>Moon in Vishakha</Description>
		<Effect>Visakha-Jealous, avaricious, handsome, clever speaker and quarrelsome, or maker of money.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Vishakha;</Rule>
	</YogaConfig>

	<!--  17  -->
	<YogaConfig>
		<Description>Moon in Anuradha</Description>
		<Effect>Anuradha-Master or chief, living in foreign countries, not able to bear hunger and fond of traveling.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Anuradha;</Rule>
	</YogaConfig>

	<!--  18  -->
	<YogaConfig>
		<Description>Moon in Jeshta</Description>
		<Effect>Jyeshta-Few friends, contented, charitable, very irritable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Jeshta;</Rule>
	</YogaConfig>

	<!--  19  -->
	<YogaConfig>
		<Description>Moon in Moola</Description>
		<Effect>Moola-Proud, rich happy, good, steady and enjoying.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Moola;</Rule>
	</YogaConfig>

	<!--  20  -->
	<YogaConfig>
		<Description>Moon in Purva Shadha</Description>
		<Effect>Purvashada-Good and pleasant wife, proud and a steady friend.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaShadha;</Rule>
	</YogaConfig>

	<!--  21  -->
	<YogaConfig>
		<Description>Moon in UttaraShadha</Description>
		<Effect>Uttarashada-Polite, knowing, virtuous, many friends, grateful and popular.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraShadha;</Rule>
	</YogaConfig>

	<!--  22  -->
	<YogaConfig>
		<Description>Moon in Sravana</Description>
		<Effect>Sravana-Rich surroundings, learned, good and liberal or liberal to wife, wealthy and renowned.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Sravana;</Rule>
	</YogaConfig>

	<!--  23  -->
	<YogaConfig>
		<Description>Moon in Dhanishta</Description>
		<Effect>Dhanishta-Liberal, rich, courageous, fond of music and money.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Dhanishta;</Rule>
	</YogaConfig>

	<!--  24  -->
	<YogaConfig>
		<Description>Moon in Satabishak</Description>
		<Effect>Satabhisha-Plain and truthful, striken from sorrow through females, etc., killer of enemies, adventurous and irreconcilable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Satabishak;</Rule>
	</YogaConfig>

	<!--  25  -->
	<YogaConfig>
		<Description>Moon in Purva Bhadra</Description>
		<Effect>Poorvabhadra-Sorrowful, loss of money through females, skilful and miserly.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == PurvaBhadra;</Rule>
	</YogaConfig>

	<!--  26  -->
	<YogaConfig>
		<Description>Moon in Uttara Bhadra</Description>
		<Effect>Uttarabhadra-Good and witty speaker in society and meetings, happy, many children and grandchildren, successful over enemies and charitable.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == UttaraBhadra;</Rule>
	</YogaConfig>

	<!--  27  -->
	<YogaConfig>
		<Description>Moon in Revati</Description>
		<Effect>Revati-Well- developed organs, popular, courageous, clean and wealthy. developed organs, popular, courageous, clean and wealthy.</Effect>
		<Source>Brihat Jataka</Source><Group>Nakshatra position</Group>
		<AllowHigherVargas>false</AllowHigherVargas>
		<Rule>return getNakshatra( Moon ) == Revati;</Rule>
	</YogaConfig>

</YogaConfigGroup>

=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/yogas/10AscendantMantreswar.xml
<?xml version="1.0"?>
<!DOCTYPE YogaConfigGroup SYSTEM "YogaConfigGroup.dtd">
<YogaConfigGroup>

<!-- Ascendant in Aries -->
	<YogaConfig> 
		<Description>Ascendant in Aries</Description>
		<Effect>If the Ascendant falls in Aries, the native will have round eyes. His knees will be weak and he will have aggressive temperament but he will be afraid of water. He will be active and will always be moving about. His limbs will be bruised. He will eat sparigly and will be passionate. He will speak falsehoods.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Aries;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Taurus -->
	<YogaConfig> 
		<Description>Ascendant in Taurus</Description>
		<Effect>The person born with Taurus as the Ascendant, will have plumply thighs and a big face. He will be engaged in agricultural ventures. He will be happy in the middle and last portions of his life. He will be fond of enjoying young women. He will be of sacrificing and forgiving nature, will be capable of endowing hardships and will possess cattle. He will have marks or moles on the back, face and sides.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Taurus;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Gemini -->
	<YogaConfig> 
		<Description>Ascendant in Gemini</Description>
		<Effect>When the Ascedant is Gemini, the native will have balck eyes and curly hair. He will enjoy association with women and will have thick neck and many friends. He will be intelligent and mind reader. His nose will be elevated and he will be fond of music and dancing. He will like to remain indoors.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Gemini;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Cancer -->
	<YogaConfig> 
		<Description>Ascendant in Cancer</Description>
		<Effect>Person with Cancer as the Ascendant will be henpacked. He will have a thick neck and will be fond of making friendships. He will possess many houses and will be wealthy. His waist will be thick but he will be short statured. He will be intelligent and fond of watery sports like swimming etc. He will walk fast and will have few sons. He will be crooked.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Cancer;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Leo -->
	<YogaConfig> 
		<Description>Ascendant in Leo</Description>
		<Effect>A person whose Ascendant is Leo will have reddish eyes, large chin and broad face. He will be arrogant, Powerful valiant, firm minded and obedient to his mother. He will be fond of roaming about in forests and hills. He will get angry on trifles.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Leo;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Virgo -->
	<YogaConfig> 
		<Description>Ascendant in Virgo</Description>
		<Effect>The person born with Virgo as the Ascendant, will be truthful and will speak kindly. His eyes will be full of bashfulness and will be immediately liked by others. He will be well versed in Shastras and will take advantage of other people's houses and wealth. His arms and shoulders will be drooped and will possess few sons.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Virgo;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Libra -->
	<YogaConfig> 
		<Description>Ascendant in Libra</Description>
		<Effect>If the Ascendant be Libra, the person born will rever gods, and Brahmins but he will be active and will possess a lean and thin body. He will be tall in stature, deft in trading, patient and intent on being first. He will often have two names. He will have few children and he will be fond of wandering. He will be brave, merciless and impartial In his arguments.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Libra;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Scorpio -->
	<YogaConfig> 
		<Description>Ascendant in Scorpio</Description>
		<Effect>The person with Scorpio Ascendant at birth, will have rounded thighs and knees. His chest will be broad and eyes expansive. He will suffer from diseases from an early age. He will beseperated from his parents and preceptor. He will indulge In cruel actions and will be honoured by the king. His feet will bear marks of lotus.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Scorpio;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Sagittarius -->
	<YogaConfig> 
		<Description>Ascendant in Sagittarius</Description>
		<Effect>The person with Sagittarius Ascendant at birth â€” His face and neck will be long and his nose and ears will be big. He will always keep himself engaged in some work or the other. He will be eloquent in speech and self sacrificing. He will have a short stature. He will be courageous and will overcome his enemies. He will be wealthy and favourite of the king. He can be won over by persuation and kindness.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Sagittarius;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Capricorn -->
	<YogaConfig> 
		<Description>Ascendant in Capricorn</Description>
		<Effect>When Capricorn is the Ascendant at birth, his lower limbs will be weak. He will have vitality. He will accept other people's advice but will be lazy by nature. He will indulge in affairs with old women of the forbidden category. He will be a religious hypocrite. He will be fond of wandering. He will be fortunate but shameless. He will suffer from wind-diseases.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Capricorn;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Aquarius -->
	<YogaConfig> 
		<Description>Ascendant in Aquarius</Description>
		<Effect>The person at whose birth Aquarius is the Ascendant, will commit sinful actions secretly. He will have little wealth, will be greedy and eager to usurp or utilise other people's money. He will endure long marches on road and will be clever in causing hurt to others. He will have a body like a water pot. He will be fond of perfumes and flowers. His financial position will be of a fluctuating nature.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Aquarius;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 

<!-- Ascendant in Pisces -->
	<YogaConfig> 
		<Description>Ascendant in Pisces</Description>
		<Effect>The Pisces ascendant native will have a beautiful and symmetrical body. His eyes will be very attractive. He will be learned, grateful, satisfied with his wife and fortune. He will have financial gains from selling produce of the seas. He will overcome his enemies.</Effect>
		<Source>Phala Deepika</Source>
		<Group>Ascendant</Group>
		<Rule>return getRasi( Ascendant ) == Pisces;</Rule>
		<AllowHigherVargas>true</AllowHigherVargas>
	</YogaConfig> 
</YogaConfigGroup>
