=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/MultipleViewConfigs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MultipleViewConfigs (MultipleViewConfig)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MultipleViewConfig (Window|Description|Name)*>
<!ATTLIST MultipleViewConfig
    SizeY CDATA #IMPLIED
    SizeX CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Window (Notebook|Splitter)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Splitter (SashPos|Window2|Window1|SashPosPercent|SplitDirection)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SplitDirection (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SashPosPercent (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Window1 (Splitter|Widget)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Widget (VargaList|ColCount|RowCount|ViewType|Vedic|TextMode|Varga|ShowToolbar)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TextMode (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Varga (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Vedic (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ShowToolbar (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Window2 (Widget|Splitter)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ViewType (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT RowCount (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ColCount (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VargaList (VargaItem)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VargaItem (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Notebook (Page)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Page (Widget|Splitter|Name)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SashPos (#PCDATA)>

=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/MultipleViewConfigs.xml
<?xml version="1.0"?>
<!DOCTYPE MultipleViewConfigs SYSTEM "MultipleViewConfigs.dtd">

<!-- See DTD for documentation -->
<MultipleViewConfigs>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Vedic Simple</Name>
    <Description>All you really need: planets, Rasi, Navamsa and Dasa tree</Description>
    <Window>
      <Splitter>
        <SplitDirection>Vertical</SplitDirection>
        <SashPosPercent>30</SashPosPercent>
        <Window1>
          <Widget>
            <ViewType>GridView</ViewType>
            <Vedic>true</Vedic>
          </Widget>
        </Window1>
        <Window2>
          <Splitter>
            <SplitDirection>Vertical</SplitDirection>
            <SashPosPercent>50</SashPosPercent>
            <Window1>
              <Widget>
                <ViewType>GraphicGridView</ViewType>
                <RowCount>2</RowCount>
                <ColCount>1</ColCount>
                <Vedic>true</Vedic>
                <VargaList>
                  <VargaItem>0</VargaItem>
                  <VargaItem>1</VargaItem>
                </VargaList>
              </Widget>
            </Window1>
            <Window2>
              <Widget>
                <ViewType>DasaView</ViewType>
              </Widget>
            </Window2>
          </Splitter>
        </Window2>
      </Splitter>
    </Window>
  </MultipleViewConfig>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Vedic Bhava</Name>
    <Description>Planets, Rasi, Bhava and Dasa tree</Description>
    <Window>
      <Splitter>
        <SplitDirection>Vertical</SplitDirection>
        <SashPosPercent>30</SashPosPercent>
        <Window1>
          <Widget>
            <ViewType>GridView</ViewType>
            <Vedic>true</Vedic>
          </Widget>
        </Window1>
        <Window2>
          <Splitter>
            <SplitDirection>Vertical</SplitDirection>
            <SashPosPercent>50</SashPosPercent>
            <Window1>
              <Widget>
                <ViewType>GraphicGridView</ViewType>
                <RowCount>2</RowCount>
                <ColCount>1</ColCount>
                <Vedic>true</Vedic>
                <VargaList>
                  <VargaItem>0</VargaItem>
                  <VargaItem>18</VargaItem>
                </VargaList>
              </Widget>
            </Window1>
            <Window2>
              <Widget>
                <ViewType>DasaView</ViewType>
              </Widget>
            </Window2>
          </Splitter>
        </Window2>
      </Splitter>
    </Window>
  </MultipleViewConfig>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Vedic Comprehensive</Name>
    <Description>All Vedic views in one window</Description>
    <Window>
      <Notebook>

				<!-- PAGE 1 -->
        <Page>
          <Name>Main</Name>
          <Splitter>
            <SplitDirection>Vertical</SplitDirection>
            <SashPosPercent>30</SashPosPercent>
            <Window1>
              <Widget>
                <ViewType>GridView</ViewType>
                <Vedic>true</Vedic>
              </Widget>
            </Window1>
            <Window2>
              <Splitter>
                <SplitDirection>Vertical</SplitDirection>
                <SashPosPercent>50</SashPosPercent>
                <Window1>
                  <Widget>
                    <ViewType>GraphicGridView</ViewType>
                    <RowCount>2</RowCount>
                    <ColCount>1</ColCount>
                    <Vedic>true</Vedic>
                    <VargaList>
                      <VargaItem>0</VargaItem>
                      <VargaItem>1</VargaItem>
                    </VargaList>
                  </Widget>
                </Window1>
                <Window2>
                  <Widget>
                    <ViewType>DasaView</ViewType>
                  </Widget>
                </Window2>
              </Splitter>
            </Window2>
          </Splitter>
        </Page>

				<!-- PAGE 2 -->
        <Page>
          <Name>Shad Varga</Name>
          <Widget>
            <ViewType>GraphicGridView</ViewType>
            <RowCount>2</RowCount>
            <ColCount>3</ColCount>
            <Vedic>true</Vedic>
            <VargaList>
              <VargaItem>0</VargaItem>
              <VargaItem>2</VargaItem>
              <VargaItem>3</VargaItem>
              <VargaItem>1</VargaItem>
              <VargaItem>9</VargaItem>
              <VargaItem>14</VargaItem>
            </VargaList>
          </Widget>
        </Page>

				<!-- PAGE 3 -->
        <Page>
          <Name>Varga (2)</Name>
          <Widget>
            <ViewType>GraphicGridView</ViewType>
            <RowCount>2</RowCount>
            <ColCount>3</ColCount>
            <Vedic>true</Vedic>
            <VargaList>
              <VargaItem>4</VargaItem>
              <VargaItem>6</VargaItem>
              <VargaItem>8</VargaItem>
              <VargaItem>10</VargaItem>
              <VargaItem>11</VargaItem>
              <VargaItem>12</VargaItem>
            </VargaList>
          </Widget>
        </Page>

				<!-- PAGE 4 -->
        <Page>
          <Name>Varga (3)</Name>
          <Widget>
            <ViewType>GraphicGridView</ViewType>
            <RowCount>2</RowCount>
            <ColCount>3</ColCount>
            <Vedic>true</Vedic>
            <VargaList>
              <VargaItem>13</VargaItem>
              <VargaItem>15</VargaItem>
              <VargaItem>16</VargaItem>
              <VargaItem>17</VargaItem>
              <VargaItem>18</VargaItem>
              <VargaItem>19</VargaItem>
            </VargaList>
          </Widget>
        </Page>

				<!-- PAGE 5 -->
        <Page>
          <Name>Text</Name>
          <Widget>
            <ViewType>TextView</ViewType>
          </Widget>
        </Page>

				<!-- PAGE 6 -->
        <Page>
          <Name>Graphical Dasa</Name>
          <Splitter>
            <SplitDirection>Horizontal</SplitDirection>
            <SashPos>450</SashPos>
            <Window1>
              <Widget>
                <ViewType>GraphicalDasaView</ViewType>
              </Widget>
            </Window1>
            <Window2>
              <Widget>
                <ViewType>GraphicGridView</ViewType>
                <RowCount>1</RowCount>
                <ColCount>2</ColCount>
                <Vedic>true</Vedic>
                <VargaList>
                  <VargaItem>0</VargaItem>
                  <VargaItem>1</VargaItem>
                </VargaList>
              </Widget>
            </Window2>
          </Splitter>
        </Page>

				<!-- PAGE 7 -->
        <Page>
          <Name>Ashtaka Varga</Name>
          <Widget>
            <ViewType>AshtakaVargaView</ViewType>
          </Widget>
        </Page>

				<!-- PAGE 8 -->
        <Page>
          <Name>Yogas</Name>
          <Widget>
            <ViewType>YogaView</ViewType>
          </Widget>
        </Page>

				<!-- PAGE 9 -->
        <Page>
          <Name>Sarvatobhadra</Name>
          <Widget>
            <ViewType>SbcView</ViewType>
          </Widget>
        </Page>
        <Page>
          <Name>Transit</Name>
          <Widget>
            <ViewType>TransitView</ViewType>
          </Widget>
        </Page>

				<!-- PAGE 10 -->
				<!--
        <Page>
          <Name>Shadbala</Name>
          <Widget>
            <ViewType>ShadBalaView</ViewType>
          </Widget>
        </Page-->

				<!-- PAGE 11 -->
        <Page>
          <Name>Tajaka/Solar</Name>
          <Widget>
            <ViewType>SolarView</ViewType>
            <Vedic>true</Vedic>
          </Widget>
        </Page>
      </Notebook>
    </Window>
  </MultipleViewConfig>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Western Simple</Name>
    <Description>Planets (left) and western chart (right)</Description>
    <Window>
      <Splitter>
        <SplitDirection>Vertical</SplitDirection>
        <SashPosPercent>30</SashPosPercent>
        <Window1>
          <Widget>
            <ViewType>GridView</ViewType>
            <Vedic>false</Vedic>
          </Widget>
        </Window1>
        <Window2>
          <Widget>
            <ViewType>GraphicView</ViewType>
            <Vedic>false</Vedic>
          </Widget>
        </Window2>
      </Splitter>
    </Window>
  </MultipleViewConfig>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Western/Aspects left</Name>
    <Description>Planets and aspects (left), western chart (right)</Description>
    <Window>
      <Splitter>
        <SplitDirection>Vertical</SplitDirection>
        <SashPosPercent>30</SashPosPercent>
        <Window1>
          <Splitter>
            <SplitDirection>Horizontal</SplitDirection>
            <SashPosPercent>50</SashPosPercent>
            <Window1>
              <Widget>
                <ViewType>GridView</ViewType>
                <Vedic>false</Vedic>
              </Widget>
            </Window1>
            <Window2>
              <Widget>
                <ViewType>TextView</ViewType>
                <TextMode>15</TextMode>
                <ShowToolbar>false</ShowToolbar>
                <Vedic>false</Vedic>
              </Widget>
            </Window2>
          </Splitter>
        </Window1>
        <Window2>
          <Widget>
            <ViewType>GraphicView</ViewType>
            <Vedic>false</Vedic>
          </Widget>
        </Window2>
      </Splitter>
    </Window>
  </MultipleViewConfig>
  <MultipleViewConfig SizeX="1000" SizeY="600">
    <Name>Western/Aspects right</Name>
    <Description>Western chart (left), planets and aspects (right)</Description>
    <Window>
      <Splitter>
        <SplitDirection>Vertical</SplitDirection>
        <SashPosPercent>70</SashPosPercent>
        <Window1>
          <Widget>
            <ViewType>GraphicView</ViewType>
            <Vedic>false</Vedic>
          </Widget>
        </Window1>
        <Window2>
          <Splitter>
            <SplitDirection>Horizontal</SplitDirection>
