=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/VedicChartConfigs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VedicChartConfigs (VedicChartConfig)+>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT VedicChartConfig (MarkedFieldBrush|DoFloodFill|OuterZodiac|Extends|Name|Description|OuterLineWidth|DoubleOuterLine|UseTextColors|UseSignColors|LineWidth|FgColor|SignBgColor|BgColor|TextColor|MarkedFieldColor|BgImage)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterLineWidth (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DoubleOuterLine (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT UseTextColors (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT UseSignColors (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT LineWidth (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT FgColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SignBgColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BgColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT TextColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MarkedFieldColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BgImage (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Extends (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterZodiac (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DoFloodFill (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT MarkedFieldBrush (#PCDATA)>

=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/VedicChartConfigs.xml
<?xml version="1.0"?>
<!DOCTYPE VedicChartConfigs SYSTEM "VedicChartConfigs.dtd">
<VedicChartConfigs>
  <VedicChartConfig>
    <Name>Default</Name>
    <Description>Default</Description>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Double Frame</Name>
    <OuterLineWidth>1</OuterLineWidth>
    <DoubleOuterLine>true</DoubleOuterLine>
    <UseTextColors>false</UseTextColors>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Minimal/No Frame</Name>
    <OuterLineWidth>0</OuterLineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Colored Signs/No borders</Name>
    <OuterLineWidth>0</OuterLineWidth>
    <UseSignColors>true</UseSignColors>
    <OuterLineWidth>0</OuterLineWidth>
    <LineWidth>0</LineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Colored</Name>
    <UseSignColors>true</UseSignColors>
    <FgColor>black</FgColor>
    <OuterLineWidth>2</OuterLineWidth>
    <LineWidth>0</LineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Colored/Red Style</Name>
    <UseSignColors>true</UseSignColors>
    <OuterLineWidth>0</OuterLineWidth>
    <SignBgColor>#de402b;#eaaaa2</SignBgColor>
    <LineWidth>0</LineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Yellow</Name>
    <BgColor>black</BgColor>
    <TextColor>yellow</TextColor>
    <FgColor>yellow</FgColor>
    <MarkedFieldColor>blue</MarkedFieldColor>
    <OuterLineWidth>3</OuterLineWidth>
    <LineWidth>2</LineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Madera</Name>
    <FgColor>white</FgColor>
    <TextColor>white</TextColor>
    <BgImage>madera.jpg</BgImage>
    <LineWidth>3</LineWidth>
    <OuterLineWidth>3</OuterLineWidth>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Too Big</Name>
    <Description></Description>
    <Extends>Yellow</Extends>
    <BgColor>black</BgColor>
    <OuterZodiac>108</OuterZodiac>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Wallpaper</Name>
    <Description>A simple wallpaper</Description>
    <Extends>Yellow</Extends>
    <BgColor>black</BgColor>
    <BgImage>wallpaper.jpg</BgImage>
    <DoFloodFill>false</DoFloodFill>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Marble</Name>
    <Extends>Yellow</Extends>
    <BgImage>marble.jpg</BgImage>
    <BgColor>black</BgColor>
    <TextColor>black</TextColor>
    <FgColor>black</FgColor>
  </VedicChartConfig>
  <VedicChartConfig>
    <Name>Stars</Name>
    <Extends>Yellow</Extends>
    <MarkedFieldBrush>5</MarkedFieldBrush>
    <MarkedFieldColor>blue</MarkedFieldColor>
    <BgImage>stars.jpg</BgImage>
  </VedicChartConfig>
</VedicChartConfigs>
