=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/WesternChartConfigs.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT WesternChartConfigs (WesternChartConfig)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT WesternChartConfig (HouseColor|PlanetColor|PaintHouseNumbers|Paint5DegCircle|SymbolType|OuterHouse|InnerHouse|PlanetMarkerLength|InnerAngleMarker|OuterAngleMarker|AspectRadius|PlanetRadius|OuterZodiac|ZodiacDegree5|ZodiacDegree1|InnerZodiac|Name|RotateSymbols|SymbolZoomFactor|BgColor|FgColor|CircleLineWidth|Description|BgImage|DoFloodFill|SignColor|PaintOuterHouseCircle|PaintInnerHouseCircle|Paint1DegCircle)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT InnerZodiac (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ZodiacDegree1 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT ZodiacDegree5 (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterZodiac (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PlanetRadius (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT AspectRadius (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterAngleMarker (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT InnerAngleMarker (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PlanetMarkerLength (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT InnerHouse (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT OuterHouse (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SymbolType (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT RotateSymbols (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SymbolZoomFactor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BgColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT FgColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT CircleLineWidth (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Description (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT BgImage (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DoFloodFill (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT SignColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PaintOuterHouseCircle (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PaintInnerHouseCircle (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Paint1DegCircle (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT Paint5DegCircle (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PaintHouseNumbers (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT PlanetColor (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT HouseColor (#PCDATA)>

=== nishp/qt-utilities/trunk/yaaa/src/maitreya/xml/WesternChartConfigs.xml
<?xml version="1.0"?>
<!DOCTYPE WesternChartConfigs SYSTEM "WesternChartConfigs.dtd">
<WesternChartConfigs>
  <WesternChartConfig>
    <Name>Default</Name>
    <InnerZodiac>79</InnerZodiac>
    <ZodiacDegree1>81</ZodiacDegree1>
    <ZodiacDegree5>83</ZodiacDegree5>
    <OuterZodiac>92</OuterZodiac>
    <PlanetRadius>73</PlanetRadius>
    <AspectRadius>55</AspectRadius>
    <OuterAngleMarker>97</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>55</InnerHouse>
    <OuterHouse>79</OuterHouse>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Big Signs</Name>
    <InnerZodiac>69</InnerZodiac>
    <ZodiacDegree1>71</ZodiacDegree1>
    <ZodiacDegree5>73</ZodiacDegree5>
    <OuterZodiac>92</OuterZodiac>
    <PlanetRadius>62</PlanetRadius>
    <AspectRadius>40</AspectRadius>
    <SymbolType>0</SymbolType>
    <InnerHouse>40</InnerHouse>
    <OuterHouse>69</OuterHouse>
    <OuterAngleMarker>97</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <RotateSymbols>True</RotateSymbols>
    <SymbolZoomFactor>250</SymbolZoomFactor>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Big Signs 2</Name>
    <InnerZodiac>69</InnerZodiac>
    <ZodiacDegree1>71</ZodiacDegree1>
    <ZodiacDegree5>73</ZodiacDegree5>
    <OuterZodiac>92</OuterZodiac>
    <PlanetRadius>62</PlanetRadius>
    <AspectRadius>40</AspectRadius>
    <OuterAngleMarker>97</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>40</InnerHouse>
    <OuterHouse>69</OuterHouse>
    <SymbolType>1</SymbolType>
    <RotateSymbols>True</RotateSymbols>
    <SymbolZoomFactor>250</SymbolZoomFactor>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Houses Outside</Name>
    <InnerZodiac>74</InnerZodiac>
    <ZodiacDegree1>76</ZodiacDegree1>
    <ZodiacDegree5>78</ZodiacDegree5>
    <OuterZodiac>85</OuterZodiac>
    <PlanetRadius>68</PlanetRadius>
    <AspectRadius>50</AspectRadius>
    <OuterAngleMarker>97</OuterAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>85</InnerHouse>
    <OuterHouse>93</OuterHouse>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Planets in Houses</Name>
    <InnerZodiac>74</InnerZodiac>
    <ZodiacDegree1>76</ZodiacDegree1>
    <ZodiacDegree5>78</ZodiacDegree5>
    <OuterZodiac>85</OuterZodiac>
    <PlanetRadius>68</PlanetRadius>
    <AspectRadius>50</AspectRadius>
    <InnerAngleMarker>50</InnerAngleMarker>
    <OuterAngleMarker>97</OuterAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>50</InnerHouse>
    <OuterHouse>93</OuterHouse>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Houses Inside</Name>
    <InnerZodiac>81</InnerZodiac>
    <ZodiacDegree1>83</ZodiacDegree1>
    <ZodiacDegree5>85</ZodiacDegree5>
    <OuterZodiac>95</OuterZodiac>
    <PlanetRadius>65</PlanetRadius>
    <AspectRadius>55</AspectRadius>
    <OuterAngleMarker>100</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>72</InnerHouse>
    <OuterHouse>81</OuterHouse>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Houses in Center</Name>
    <InnerZodiac>81</InnerZodiac>
    <ZodiacDegree1>83</ZodiacDegree1>
    <ZodiacDegree5>85</ZodiacDegree5>
    <OuterZodiac>95</OuterZodiac>
    <PlanetRadius>75</PlanetRadius>
    <AspectRadius>55</AspectRadius>
    <OuterAngleMarker>100</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>55</InnerHouse>
    <OuterHouse>62</OuterHouse>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Astrolog</Name>
    <InnerZodiac>79</InnerZodiac>
    <ZodiacDegree1>81</ZodiacDegree1>
    <ZodiacDegree5>83</ZodiacDegree5>
    <OuterZodiac>92</OuterZodiac>
    <PlanetRadius>73</PlanetRadius>
    <AspectRadius>55</AspectRadius>
    <OuterAngleMarker>97</OuterAngleMarker>
    <InnerAngleMarker>50</InnerAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>55</InnerHouse>
    <OuterHouse>79</OuterHouse>
    <BgColor>black</BgColor>
    <FgColor>white</FgColor>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Yellow</Name>
    <BgColor>black</BgColor>
    <FgColor>yellow</FgColor>
    <CircleLineWidth>5</CircleLineWidth>
    <RotateSymbols>True</RotateSymbols>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Madera</Name>
    <Description>A walnut-like theme</Description>
    <FgColor>white</FgColor>
    <BgImage>madera.jpg</BgImage>
    <CircleLineWidth>5</CircleLineWidth>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Wallpaper</Name>
    <BgColor>black</BgColor>
    <FgColor>yellow</FgColor>
    <CircleLineWidth>5</CircleLineWidth>
    <BgImage>wallpaper.jpg</BgImage>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Marble</Name>
    <BgColor>white</BgColor>
    <FgColor>black</FgColor>
    <CircleLineWidth>1</CircleLineWidth>
    <BgImage>marble.jpg</BgImage>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Too Big</Name>
    <BgColor>black</BgColor>
    <FgColor>yellow</FgColor>
    <CircleLineWidth>5</CircleLineWidth>
    <OuterZodiac>110</OuterZodiac>
    <BgImage>wallpaper.jpg</BgImage>
    <DoFloodFill>false</DoFloodFill>
    <SymbolZoomFactor>250</SymbolZoomFactor>
    <RotateSymbols>True</RotateSymbols>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Stars</Name>
    <Description>Looking into the stars</Description>
    <BgColor>black</BgColor>
    <FgColor>yellow</FgColor>
    <CircleLineWidth>5</CircleLineWidth>
    <BgImage>stars.jpg</BgImage>
  </WesternChartConfig>
  <WesternChartConfig>
    <Name>Nostalgy</Name>
    <Description>Similar to old Maitreya 4.2 style</Description>
    <InnerZodiac>70</InnerZodiac>
    <SymbolType>2</SymbolType>
    <ZodiacDegree1>72</ZodiacDegree1>
    <ZodiacDegree5>74</ZodiacDegree5>
    <SignColor>black</SignColor>
    <OuterZodiac>85</OuterZodiac>
    <PlanetRadius>64</PlanetRadius>
    <AspectRadius>70</AspectRadius>
    <OuterAngleMarker>97</OuterAngleMarker>
    <PlanetMarkerLength>2</PlanetMarkerLength>
    <InnerHouse>40</InnerHouse>
    <OuterHouse>93</OuterHouse>
    <PaintOuterHouseCircle>false</PaintOuterHouseCircle>
    <PaintInnerHouseCircle>true</PaintInnerHouseCircle>
    <Paint1DegCircle>true</Paint1DegCircle>
    <Paint5DegCircle>true</Paint5DegCircle>
    <PaintHouseNumbers>false</PaintHouseNumbers>
    <PlanetColor>black</PlanetColor>
    <HouseColor>black</HouseColor>
    <SignColor>black</SignColor>
  </WesternChartConfig>
</WesternChartConfigs>
